functional:
  - The user should be able to search for products by keyword or category.
  - The user should be able to filter products by price, color, size, brand.
  - The user should be able to view the products in the catalog using pagination and view detailed information about the product.
    In both cases, the following information is displayed - name, rating, price with and without a discount.
  - The user should be able to add items to the cart and view the contents of the cart.
  - After adding a product to the cart, the user can continue to select products in the catalog.
  - On the cart page, the user can remove an item from the cart, continue to select items in the catalog.
  - When placing an order, you are redirected to the payment page.
  - The shopping cart is stored in the browser session.
  - The online store is a SPA application that does not reload the page.

non-functional:
  - The website should be designed with usability in mind and optimized for speed.
  - The site must be secure and protect user data.
  - The site must be able to handle a large amount of traffic.
  - The site must have a mobile version.
  - The site must be tested for compatibility with the latest versions of browsers.
  - The site must be accessible on various devices.
  - A key feature of the store will be adaptive layout so that it is convenient on mobile devices.

implicit:
  - Saving the shopping cart via ckookies when the user exits the site
  - Search by hashtag
  - Display the size of the discount on the product page.
  - The interface is available in two languages - Russian and English.
